### ISSUE TITLE
Define flow for creating application from samples

### ISSUE THREAD

**Issue by elsony** [redhat-appstudio/application-service#2]
Define flow for creating applications from samples:

1. Catalog of available service type
2. Creation using samples/starter projects from each service type
3. Sample of a multi-service application
4. Linking services within the same application (stretch)

From: https://issues.redhat.com/browse/DEVHAS-2

**Comment by johnmcollier** [comment]
Flow for creating applications from sample (and importing from Git and Image as well):
![HAS Create Application Flow (4)](https://user-images.githubusercontent.com/6880023/135107017-ee0369a6-5298-4e50-bc54-78b285df9eca.jpg)

Corresponding Miro board can be found here: https://miro.com/app/board/o9J_lvkBFXE=/ (will need Red Hat login to view)

**Comment by johnmcollier** [comment]
I think this one can be closed out?

**Comment by elsony** [comment]
Closing it since we are using Jira for tracking issues
