### ISSUE TITLE
Define APIs for creating application from samples

### ISSUE THREAD

**Issue by elsony** [redhat-appstudio/application-service#3]
Define the HAS API for creating applications from samples. API includes:

1. Query existing samples
2. Create an application
3. Add service to the application
5. Save a model to the repository

From: https://issues.redhat.com/browse/DEVHAS-3

**Comment by johnmcollier** [comment]
API doc (will need Red Hat login to view): https://docs.google.com/document/d/1udOFeK5wGf_MMAnQMj6mOc0CWvS4qsld1ov2L34ZcPo/edit?usp=sharing

**Comment by elsony** [comment]
Closing it since we are using Jira for tracking issues
